resume:
load_encoder: True
load_fuse_generator: True
device: cuda:0    # usually use cuda:3 but for job use 0
K: 1 # temporal sequence length - no temporal data used here
deterministic: False

train:
  lr: 1e-3
  num_epochs: 50
  batch_size: 8 # 32
  num_workers: 4
  log_path: logs/smirkhair
  log_append_timestamp: True
  log_losses_every: 0 # 10    # this is per # batch
  visualize_phase:
    train: False
    val: True
  visualize_every: 50   # num_batch
  mask_ratio: 0.01  # pixel to be retained inside the hair mask, ratio is over the whole image
  mask_dilation_radius: 10 # dilation of the initial hair mask
  save_every: 2 # save model every n epochs
  use_wandb: False
  Ke: 1 # number of repeated frames for 2nd cycle path
  use_base_model_for_regularization: True  # use the base model for regularization - when False the regularization is wrt zero
  resume_epoch: 0

  loss_weights:
    perceptual_vgg_loss: 10.0  # RECONSTRUCTION - perceptual vgg loss weight
    reconstruction_loss: 10.0  # RECONSTRUCTION - l1 loss weight
    strand_regularization: 1e-2
    depth_regularization: 1e-2
    cycle_loss: 1.0  # CYCLE loss - NOT implemented
    strand_local_regularization: 0 #1e-4   # local smooth loss
    strand_local_kernel: 3   # local smooth loss
    strand_local_stride: 1   # local smooth loss
    strand_local_padding: 1   # local smooth loss
    depth_local_regularization: 0.0     # local smooth loss
    depth_local_kernel: 3

  optimize_hairstrand: True
  optimize_hairdepth: False   # has depth but no graph

  # automatically tunable hyperparameters - just declared here
  freeze_encoder_in_second_path: False
  freeze_generator_in_second_path: False
  freeze_smirk_encoder: True

# architectural details
arch:
  encoder_norm_strand_magnitude: True
  enable_fuse_generator: True 
  depth_branch: True     # No depth map
  num_expression: 50
  num_shape: 300
  use_eyelids: True

# hairstep
checkpoint_img2strand: /home/alrivero/HairStep/checkpoints/img2hairstep/img2strand.pth
checkpoint_img2depth: /home/alrivero/HairStep/checkpoints/img2hairstep/img2depth.pth

# smirk pretrain
checkpoint_smirk: pretrained_models/SMIRK_em1.pt
load_generator: False

dataset:
  resolution: 512

  FFHQ_path: /data/add_disk3/arivero/images1024x1024/images
  FFHQ_meta_path: /data/add_disk3/arivero/ffhq-dataset-v2.json
  FFHQ_hairmask: /data/add_disk3/arivero/images1024x1024/processed/hairstep/seg
  FFHQ_bodymask: /data/add_disk3/arivero/images1024x1024/processed/hairstep/body_img

  # percentage of data to use for each dataset
  FFHQ_percentage: 1    # sampling weight when training multiple datasets

  # using subset of the dataset only
  FFHQ_percentage_subset: 0.1 # 0.1 # 0.001 # 0.01
