resume:
load_encoder: True
load_fuse_generator: True
device: cuda:0    # usually use cuda:3 but for job use 0
K: 1 # temporal sequence length - no temporal data used here
deterministic: False

train:
  lr: 1e-3
  num_epochs: 50
  batch_size: 16 # 32
  num_workers: 4
  log_path: logs/smirkhair
  log_append_timestamp: True
  log_losses_every: 0 # 10    # this is per # batch
  visualize_phase:
    train: False
    val: True
  visualize_every: 50   # num_batch
  mask_ratio: 0.01  # pixel to be retained inside the hair mask, ratio is over the whole image
  mask_dilation_radius: 10 # dilation of the initial hair mask
  save_every: 10 # save model every n epochs
  use_wandb: False
  Ke: 1 # number of repeated frames for 2nd cycle path
  use_base_model_for_regularization: True  # use the base model for regularization - when False the regularization is wrt zero
  resume_epoch: 0

  loss_weights:
    perceptual_vgg_loss: 10.0  # RECONSTRUCTION - perceptual vgg loss weight
    reconstruction_loss: 10.0  # RECONSTRUCTION - l1 loss weight
    strand_regularization: 1e-2
    depth_regularization: 1e-2
    cycle_loss: 0.0  # CYCLE loss - NOT implemented
    # cycle_loss: 1.0  # CYCLE loss
    strand_local_regularization: 0 #1e-4   # local smooth loss
    strand_local_kernel: 3   # local smooth loss
    strand_local_stride: 1   # local smooth loss
    strand_local_padding: 1   # local smooth loss
    depth_local_regularization: 0.0     # local smooth loss
    depth_local_kernel: 3

  optimize_hairstrand: True
  optimize_hairdepth: False   # has depth but no graph

  # automatically tunable hyperparameters - just declared here
  freeze_encoder_in_second_path: False
  freeze_generator_in_second_path: False

# architectural details
arch:
  encoder_norm_strand_magnitude: True
  enable_fuse_generator: True 
  depth_branch: False     # No depth map

# hairstep
checkpoint_img2strand: /gpfs/projects/CascanteBonillaGroup/thinguyen/storage/smirk/external/HairStep/checkpoints/img2hairstep/img2strand.pth
checkpoint_img2depth: /gpfs/projects/CascanteBonillaGroup/thinguyen/storage/smirk/external/HairStep/checkpoints/img2hairstep/img2depth.pth


dataset:
  FFHQ_path: /gpfs/projects/CascanteBonillaGroup/thinguyen/datasets/FFHQ256/processed/hairstep/resized_img
  FFHQ_meta_path: /gpfs/projects/CascanteBonillaGroup/thinguyen/datasets/FFHQ256/metadata/ffhq-dataset-v2.json
  FFHQ_hairmask: /gpfs/projects/CascanteBonillaGroup/thinguyen/datasets/FFHQ256/processed/hairstep/seg
  FFHQ_bodymask: /gpfs/projects/CascanteBonillaGroup/thinguyen/datasets/FFHQ256/processed/hairstep/body_img

  # percentage of data to use for each dataset
  FFHQ_percentage: 1    # sampling weight when training multiple datasets

  # using subset of the dataset only
  FFHQ_percentage_subset: 0.1 # 0.001 # 0.01
